[theme]
base="light"
primaryColor="#2E7D32"
backgroundColor="#FFFFFF"
secondaryBackgroundColor="#F0F2F6"
textColor="#333333"
font="sans serif"

[client]
toolbarMode = "viewer"
showSidebarNavigation = false
